name:                sample
version:             0.1.0.0
github:              "marceloslacerda/sample"
license:             BSD3
author:              "Marcelo Lacerda"
maintainer:          "marceloslacerda@gmail.com"
copyright:           "BSD"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            console

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/marceloslacerda/sample#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  sample-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sample

tests:
  sample-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sample
